### ISSUE TITLE
Remove logging msg

### ISSUE THREAD

**Issue by jennijuju** [arajasek/external_staker#4]
I am sending: "0x9907b13575a63ee38edf735d9ead23acfb14c46148eca83521d68e49d45cfeebf7d3a6d1a1679115c4addbe0992bc6eb82a626e308036f7500d440ff8b97bd01", "0xea3b1f6b8612427dd23d68bd69ef89534bb182d924f6fc5e7483979d038c6883"

**Comment by arajasek** [comment]
Resolved in commit e3a56a1bd268db91181534f6a05211528c0d8e00
